### ISSUE TITLE
/root/matrix_key.pem missing

### ISSUE THREAD

**Issue by CptCurk** [YunoHost-Apps/dendrite_ynh#125]
Hello ! 

I installed dendrite, and would like to register my first user as admin (myself of course).

I've enter the Shared Secret for Registration.

and then using SSH, copy and paste this : `/opt/yunohost/dendrite/bin/create-account -config /opt/yunohost/dendrite/dendrite.yaml -username USERNAME -admin`
(replacing USERNAME of course)

but a FATAL error pop up and say that there no such file in directory : /root/matrix_key.pem

What could I do to just make it work. as simple as that. 

Thank you !

**Comment by tituspijean** [comment]
The binary is expecting to be run as the `dendrite` user. Try SSHing, then first run `sudo yunohost app shell dendrite` to open a prompt in `/opt/yunohost/dendrite` as `dendrite` user. It should find `matrix_key.pem` on its own.

**Comment by CptCurk** [comment]
parfait. 

Merci beaucoup, je ne savais pas qu'on pouvait lancer un shell sur les app dans yunohost directement.

Belle journée !
