### ISSUE TITLE
Installation failed on Debian 11

### ISSUE THREAD

**Issue by m0rtis0** [YunoHost-Apps/dendrite_ynh#25]
### Describe the bug

Installation of App Fails on Generic Debian 11

### Context

- Hardware: VPS
- YunoHost version: 4.3.6.3
- I have access to my server: Webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: latest / 0.6.5 ynh 1
- If upgrading, current package version:

### Steps to reproduce

Try to install Dendrite on YunoHost

### Expected behavior

Installation succeeds

### Logs
https://paste.yunohost.org/raw/imaloyilot

**Comment by mneiger** [comment]
same here but with more recent version 

yunohost: 
  repo: testing
  version: 11.0.6
yunohost-admin: 
  repo: testing
  version: 11.0.6
moulinette: 
  repo: testing
  version: 11.0.6
ssowat: 
  repo: testing
  version: 11.0.6

[https://paste.yunohost.org/raw/xawetezila](https://paste.yunohost.org/raw/xawetezila)

**Comment by m0rtis0** [comment]
I was able to install via CLI.

**Comment by mneiger** [comment]
> I was able to install via CLI.

I've been attempting using CLI, both stable and testing, none worked. same problem with database creation.

**Comment by mneiger** [comment]
it did work today with the latest commit :
sudo yunohost app install https://github.com/YunoHost-Apps/dendrite_ynh/tree/testing --debug

[https://paste.yunohost.org/raw/oqowaxuvul](https://paste.yunohost.org/raw/oqowaxuvul)

**Comment by mneiger** [comment]
Installed, but unable to connect element to the server nor login from external element app.

**Comment by johanbove** [comment]
Tried installing today with a failure - probably related. So awaiting the latest version being released.

Logs: https://paste.yunohost.org/raw/aheqapafom

**Comment by tituspijean** [comment]
Dear all, please try current testing branch. ;)

---

> Installed, but unable to connect element to the server nor login from external element app.

I have similar issues, #29 opened.

**Comment by mneiger** [comment]
Tested.
The dendrite server is functional but only usable as https://matrix.domain.tld:8448 as home server,  not as matrix.domain.tld
(Wuld there be a way to use just domain.tld as home server ?)
It is possible to register new users once logged on through ssowat but the user base is not populated wit yunohost users: does it access the LDAP user base?
Thanks, it's not a yunohost app yet, but we're getting there
May I provide test info?

**Comment by tituspijean** [comment]
Your other issues are covered in #1 and #29.
