### ISSUE TITLE
Server not detected by client apps

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/dendrite_ynh#29]
### Describe the bug

Auto-discovery / well-known address not working

### Steps to reproduce

Install the app and Element, set SRV DNS records... but Element won't be able to detect the server unless you specify its port.

**Comment by Gredin67** [comment]
Setting https://matrix.domain.tld:8448/ in Element config file does not work. It only works to set matrix.org in the config file and then edit the homeserver field to `https://matrix.domain.tld:8448/` each time we want to connect. 
Any workaround to make the

**Comment by tituspijean** [comment]
Instructions left in https://github.com/YunoHost-Apps/dendrite_ynh/issues/1#issuecomment-1219522718 should fix this issue.
