### ISSUE TITLE
Service not starting when installing with public option

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/dendrite_ynh#38]
When installing the app with `registration_disabled: true` the dendrite service does not start.
It raises an error to warn for spam or abuse. The service should be started with flag `-really-enable-open-registration`
I'm not sure what we want to do about it in dendrite_ynh.

I would say: 
* set installation private (SSO) defaults
* add a warning in the manifest when the user selects public
* add this flag `-really-enable-open-registration` to the systemd service start when public

```
time="2022-06-24T14:28:56+02:00" level=error msg="Configuration error: You have tried to enable open registration without any secondary verification methods (such as reCAPTCHA). By enabling open registration, you are SIGNIFICANTLY increasing the risk that your server will be used to send spam or abuse, and may result in your server being banned from some rooms. If you are ABSOLUTELY CERTAIN you want to do this, start Dendrite with the -really-enable-open-registration command line flag. Otherwise, you should set the registration_disabled option in your Dendrite config."
time="2022-06-24T14:28:56+02:00" level=fatal msg="Failed to start due to configuration errors"
```

**Comment by tituspijean** [comment]
Solved by #45
