### ISSUE TITLE
[testing] build fails

### ISSUE THREAD

**Issue by florisre** [YunoHost-Apps/dendrite_ynh#47]
### Describe the bug

Installation of the testing branch fails. The log can be found here: https://paste.yunohost.org/raw/tusekupebo

### Context

- Hardware: VPS bought online running Debian 11
- YunoHost version: 11.0.9.9
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: testing

### Steps to reproduce

```
sudo yunohost app install https://github.com/YunoHost-Apps/dendrite_ynh/tree/testing --debug
```

### Expected behavior

Installation and startup of the Dendrite server.

### Logs

https://paste.yunohost.org/raw/tusekupebo

**Comment by tituspijean** [comment]
Confirmed, hence why I had put the PR in draft mode. 😅

**Comment by tituspijean** [comment]
Actually the issue was that the requirement for Go was upped to v1.18 and the `goose` utility was dropped.
