### ISSUE TITLE
dendrite fails to start due to breaking change in 0.10.2

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/dendrite_ynh#69]
### Describe the bug

As of v0.10.3 the app fails to start after upgrade due to DB sanity check ([introduced in v0.10.2 upstream](https://newreleases.io/project/github/matrix-org/dendrite/release/v0.10.2)) failing.

This app comes with configuration allowing 100 concurrent PostgreSQL connections, my current/default PostgreSQL configuration allows 97 leading to issue on startup.

> The configured 'max_open_conns' is greater than the 97 non-superuser connections that PostgreSQL is configured to allow. This can result in bad performance or deadlocks. Please pay close attention to your configured database connection counts. If you REALLY know what you are doing and want to override this error, pass the --skip-db-sanity option to Dendrite."

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.10.1
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - upgraded v0.10.1 to v0.10.3
- Using, or trying to install package version/branch: problem occurs on v0.10.3
- If upgrading, current package version: v0.10.3 - app upgraded but failed to start.

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade dendrite
    ```
### Expected behavior

dendrite upgraded to v0.10.3, starting successfully

### Logs

[Here](https://paste.yunohost.org/raw/qovotuvaxu)

**Comment by tituspijean** [comment]
Oh dang, I had the same issue but assumed it was due to my manual tweaks on the server.

**Comment by roukydesbois** [comment]
Same here!
