### ISSUE TITLE
Server UP but server unreachable

### ISSUE THREAD

**Issue by kazukyakayashi** [YunoHost-Apps/dendrite_ynh#83]
### Describe the bug

The upgrade of Dendrite from version 0.10.7 to 0.10.8 was done without any problem, Dendrite launches well, I can connect to the server and to my account, but I can't communicate with anyone, my messages don't leave (and no error message from the Cinny client) and I don't receive anything, the server seems to be unreachable by the other servers

### Context

- Hardware: Kimsufi KS1 (OVH)
- YunoHost version: 10.0.11
- I have access to my server: yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Update Dentrite 0.10.7 to 0.10.8

### Steps to reproduce

Update of Dendrite via the Yunohost web interface.

### Logs

[Log at the launch of Dendrite](https://paste.yunohost.org/punasihoga)
[Log after an attempt to send a message](https://paste.yunohost.org/avobuqahiy)

**Comment by tituspijean** [comment]
You seem to have taken the server offline.

https://federationtester.matrix.org/#dendrite.zarchbox.ovh

Can you make sure that's it is running and that the Federation Tests are OK?

**Comment by orhtej2** [comment]
Is port 8448 open on firewall?

**Comment by kazukyakayashi** [comment]
Indeed the port was not even present in the list on the firewall page (and there was nothing in the Yunohost diagnostic) 

Thank you 👍️

**Comment by tituspijean** [comment]
Can you share your upgrade log? The TLS port should be set as needed by the install and upgrade scripts. It is not normal to have it missing from the firewall and the diagnostics.
