### ISSUE TITLE
Dendrite fails to install due to unset `$psql_version`

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/dendrite_ynh#86]
### Describe the bug

When installing Dendrite configuration fails due to
>  DEBUG - ynh_die '--message=Variable $psql_version wasn'\''t initialized when trying to replace __PSQL_VERSION__ in /etc/systemd/system/dendrite.service'
>  WARNING - Variable $psql_version wasn't initialized when trying to replace __PSQL_VERSION__ in /etc/systemd/system/dendrite.service

### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.6.2
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no, installed via WebAdmin
- Using, or trying to install package version/branch: 0.10.8~ynh2

### Steps to reproduce

    ```sh
    sudo yunohost app install dendrite
    ```
### Expected behavior

App installed

### Logs

[HERE](https://paste.yunohost.org/raw/etimukuxex)

**Comment by orhtej2** [comment]
As a side note this did not roll back the installation, at least subdomain says 'This is where Dendrite is installed.'

**Comment by ericgaspar** [comment]
I have the same error with `PSQL_VERSION` when using the config panel

**Comment by tituspijean** [comment]
> When installing Dendrite configuration

@orhtej2 can you specify which action you are doing? It seems the issue and logs are with the configuration panel, but you mention "install"...

**Comment by tituspijean** [comment]
@ericgaspar can you share your log? I cannot replicate the issue. :/

**Comment by ericgaspar** [comment]
https://paste.yunohost.org/raw/xekizabowi

**Comment by tituspijean** [comment]
Can you try upgrading the app?

```
2023-02-19 12:16:09,081: DEBUG - + source _common.sh
2023-02-19 12:16:09,082: DEBUG - ++ pkg_dependencies='postgresql postgresql-contrib'
2023-02-19 12:16:09,082: DEBUG - ++ GO_VERSION=1.18
2023-02-19 12:16:09,082: DEBUG - + source /usr/share/yunohost/helpers
```

There should be a line here that loads `$psql_version` in there. ^^

**Comment by orhtej2** [comment]
> > When installing Dendrite configuration
> 
> @orhtej2 can you specify which action you are doing? It seems the issue and logs are with the configuration panel, but you mention "install"...

It was install from scratch that failed, by configuration I meant the phase of the script after it compiled the sources.

I'm trying with 0.11.1~ynh1 now (fresh install).

**Comment by orhtej2** [comment]
Worked like a charm with 0.11.1~ynh1, closing.
