### ISSUE TITLE
Installation succesful, but can't create an account

### ISSUE THREAD

**Issue by Folaht** [YunoHost-Apps/dendrite_ynh#87]
### Describe the bug

After installing dendrite, I'm unable to create user accounts. 
And without accounts, I can't use my matrix server.

```text
[Vxnebehrzjepa dendrite]# ./bin/create-account -username folaht -admin
Enter Password:
Confirm Password:
FATA[0005] Failed to create the account:
```

### Context

- Hardware: RPi 4
- YunoHost version: 11.1.6
- I have access to my server: yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

```text
sudo yunohost app install dendrite
sudo su
cd /opt/yunohost/dendrite 
sed -i  's/registration_shared_secret: ""/registration_shared_secret: "secret"/' dendrite.yaml
./bin/create-account -username username -admin
```

### Expected behavior

"User created!"

### Logs

Not sure what would be useful here.

**Comment by orhtej2** [comment]
Did you remember to `systemctl restart dendrite` first for the config to take effect?

**Comment by Folaht** [comment]
Stupid me. I'm still recieving an error.  

```
FATA[0002] Failed to create the account: unable to get nonce: Get "http://localhost:8008/_synapse/admin/v1/register": dial tcp [::1]:8008: connect: connection refused
```

**Comment by Folaht** [comment]
Stupid me. Problem solved.

**Comment by orhtej2** [comment]
There's a comment I received via mail but is no longer (?) present here.
Is the problem solved? Did `dendrite` finish boot sequence before refusing `8008` connection?
